#!/usr/bin/env bash

FILE="duckfetch"

if [[ ! -f "./$FILE" ]]; then
    echo "The 'duckfetch' script does not exist."
    exit
fi

if [[ $(uname -o) == "Android" ]]; then
	cp ./$FILE /data/data/com.termux/files/usr/bin
else
	sudo cp ./$FILE /usr/bin
fi

echo "Installation complete. Run the 'duckfetch' command."
echo "If you have any issue, please report them in the issues tab."
